[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[font]
size = 13.0
normal = { family = "JetBrainsMono Nerd Font" }

[terminal]
shell = { program = "fish", args = ["--login", "--interactive"]}
