[tools]
"github:asdine/cueimports" = "latest"
"github:direnv/direnv" = "latest"
"github:tree-sitter/tree-sitter" = "latest"

# Cloud tools
gcloud = "latest"
aws-cli = { version = "2", symlink_bins = "true" }

# Encryption
"github:getsops/sops" = "latest"
"github:FiloSottile/age" = "latest"

# Kubernetes
k9s = "latest"
kubectl = "latest"
helm = "latest"
kube-capacity = "latest"
kubectx = "latest"
kubens = "latest"
kind = "latest"

# IaC tools
terragrunt = "latest"
opentofu = "latest"
terraform = "latest"
"npm:cdktf-cli" = "latest"

# General utilities that either are unixy or better versions of existing unix
# tools.
"github:sharkdp/hyperfine" = "latest"
hwatch = "latest"
grpcurl = "latest"
fd = "latest"
ripgrep = "latest"
bat = "latest"
jq = "latest"
just = "latest"
fzf = "latest"
delta = "latest"
"github:bvaisvil/zenith" = "latest"
"github:chasinglogic/projector" = "latest"
"github:chasinglogic/dfm" = "latest"
"npm:@google/gemini-cli" = "latest"

# For building and publishing my blog
# hugo = "latest"

# Load testing tool
"cargo:oha" = "latest"

# Container security scanning tools
grype = "latest"
syft = "latest"

# Languages
rust = "latest"
go = "latest"
python = "3.13"
"pipx:hatch" = "latest"
node = "latest"

# Language tooling
uv = "latest"
"aqua:astral-sh/ruff" = "latest"
shfmt = "latest"
shellcheck = "latest"
gomigrate = "latest"
"github:goreleaser/goreleaser" = "latest"
golangci-lint = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"npm:prettier" = "latest"
"npm:eslint" = "latest"
pipx = "latest"
ruby = "latest"
npm = "latest"
usage = "latest"
act = "latest"
fx = "latest"
gh = "latest"
"github:dundee/gdu" = "latest"
clojure = "latest"
java = "openjdk-25"
babashka = "latest"
duckdb = "latest"
tflint = "latest"
"github:sharkdp/bat" = "latest"
sops = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
